-- Align the handcrafted initial migration with Prisma's @default(uuid()) and @updatedAt semantics.
ALTER TABLE "User" ALTER COLUMN "id" DROP DEFAULT, ALTER COLUMN "updatedAt" DROP DEFAULT;
ALTER TABLE "Profile" ALTER COLUMN "id" DROP DEFAULT, ALTER COLUMN "updatedAt" DROP DEFAULT;
ALTER TABLE "Session" ALTER COLUMN "id" DROP DEFAULT;
ALTER TABLE "Media" ALTER COLUMN "id" DROP DEFAULT, ALTER COLUMN "updatedAt" DROP DEFAULT;
ALTER TABLE "Review" ALTER COLUMN "id" DROP DEFAULT, ALTER COLUMN "updatedAt" DROP DEFAULT;
ALTER TABLE "ReviewComment" ALTER COLUMN "id" DROP DEFAULT, ALTER COLUMN "updatedAt" DROP DEFAULT;
ALTER TABLE "ReviewVersion" ALTER COLUMN "id" DROP DEFAULT;
ALTER TABLE "List" ALTER COLUMN "id" DROP DEFAULT, ALTER COLUMN "updatedAt" DROP DEFAULT;
ALTER TABLE "AcquisitionHistory" ALTER COLUMN "id" DROP DEFAULT, ALTER COLUMN "updatedAt" DROP DEFAULT;
ALTER TABLE "Activity" ALTER COLUMN "id" DROP DEFAULT;
ALTER TABLE "Notification" ALTER COLUMN "id" DROP DEFAULT;
ALTER TABLE "AuditLog" ALTER COLUMN "id" DROP DEFAULT;
ALTER TABLE "Tag" ALTER COLUMN "id" DROP DEFAULT;
